#!/usr/bin/env bash
# installs Nginx and sets up an index page that has "Hello World!"

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
