#!/usr/bin/env bash
# configure nginx on server such that it returns a custom response header `X-Served-By`

HEADER_VALUE=$(hostname)
HEADER='X-Served-By'

ADD301_REDIRECT="\\\n\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}"
ADD404_NOTFOUND="error_page 404 /custom_404.html;\n\\tlocation = /custom_404.html {\n\t\t root /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"

# install nginx if not installed
sudo apt-get update
sudo apt-get -y install nginx

# setup home page
sudo chown -R "$USER":"$USER" /var/www/html
echo "Hello World!" > /var/www/html/index.html

# add redirection rule
sudo sed -i "/server_name _/a$ADD301_REDIRECT" /etc/nginx/sites-available/default

# add header and value
sudo sed -i "/server_name _/a\\\n\tadd_header $HEADER $HEADER_VALUE;" /etc/nginx/sites-available/default

# configure error pagee nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "s@$PATTERN@$ADD404_NOTFOUND@" /etc/nginx/sites-available/default #uncomment and replace

# restart nginx service
sudo service nginx restart
