#!/usr/bin/env bash
# creates file /var/run/yscript.pid
# displays "To infinity and beyond"
# Displays "I hate the kill command" when receiving a SIGTERM signal
# displays "Y U no love me?!" when receives SIGINT signal
# Delete the file above and terminates itself when recieves SIGQUIT or SIGTERM signal

handle_sigint()
{
    echo "Y U no love me?!"
}

handle_sigterm()
{
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit
}

handle_sigquit()
{
    rm -f /var/run/myscript.pid
    exit
}
trap "handle_sigint" SIGINT
trap "handle_sigterm" SIGTERM
trap "handle_sigquit" SIGQUIT

echo "$$" >> /var/run/myscript.pid

while true
    do
       echo "To infinity and beyond"
       sleep 2
    done
