#!/usr/bin/env bash
# Fixes nginx to run as an under privileged user / user with no root privilege

# set the 'user' directive to 'nginx' user
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf

# permission setting
sudo chmod 700 /etc/nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf

# make nginx default server block listen on port 8080
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default

# kill apache2 since its listening on that port and start nginx service
pkill apache2
sudo -u nginx service nginx restart

