#!/usr/bin/env bash
# Refactor the first bash script up to 7 lines or less
sudo sed -i 's/#user www-data/user nginx/' /ect/nginx/nginx.conf
sudo chmod 700 /etc.nginx/nginx.conf
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx restart

